version: '3'
services:
    client:
      container_name: angular-client
      build:
        context: ./client
        dockerfile: Dockerfile
      volumes:
        - '.:/usr/src/app'
        - '/usr/src/app/node_modules'
      depends_on:
        - app
        - mongo
      ports:
        - '4200:4200'
    app:
      container_name: docker-node-mongo
      hostname: server
      restart: always
      build: .
      ports:
        - '3000:3000'
      volumes:
        - .:/usr/src/app
      links:
        - mongo
    mongo:
      container_name: mongo_container
      image: mongo
      ports:
        - '27017:27017'
